In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import pylab
import csv
import pandas as pd

In [3]:
data=pd.read_csv(r'C:\Users\ilies\OneDrive\Bureau\Projet DATA\Predict\data\data_INSEE_clean.csv', sep=';', low_memory=False)

In [4]:
data.head()

,code,commune,pop,1_child-25,Indice_vieillissement,density_pop,evol_pop,pop-15y,pop-25y,pop-64y,...,collège,urgences,lycee,dentiste,medecin,infirmier,creche,kine,pharmacie,epahd
0,01001,L'Abergement-Clémenciat,767.0,19.1,67.5,48.1,-0.3,21.0,30.0,51.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,01002,L'Abergement-de-Varey,243.0,13.3,66.7,26.6,0.8,22.6,28.8,53.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,01004,Ambérieu-en-Bugey,14081.0,24.8,62.1,572.4,0.3,19.8,32.5,51.0,...,2.0,1.0,2.0,12.0,27.0,20.0,2.0,25.0,6.0,2.0
3,01005,Ambérieux-en-Dombes,1671.0,18.7,58.1,105.0,0.9,20.5,31.6,53.0,...,0.0,0.0,0.0,0.0,2.0,3.0,0.0,1.0,1.0,0.0
4,01006,Ambléon,110.0,28.6,173.3,18.7,-0.4,10.9,20.0,56.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
data['type_agglo'].unique()

array(['Village', 'Petit ville', 'Bourg', 'Ville moyenne', 'Grande ville',
       'Métropole'], dtype=object)

In [8]:
data.replace({'Village': 1, 'Petit ville': 2, 'Bourg': 3, 'Ville moyenne': 4,'Grande ville': 5,'Métropole' : 6}, inplace=True)
data.infer_objects(copy=False)

,code,commune,pop,1_child-25,Indice_vieillissement,density_pop,evol_pop,pop-15y,pop-25y,pop-64y,...,collège,urgences,lycee,dentiste,medecin,infirmier,creche,kine,pharmacie,epahd
0,01001,L'Abergement-Clémenciat,767.0,19.1,67.5,48.1,-0.3,21.0,30.0,51.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,01002,L'Abergement-de-Varey,243.0,13.3,66.7,26.6,0.8,22.6,28.8,53.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,01004,Ambérieu-en-Bugey,14081.0,24.8,62.1,572.4,0.3,19.8,32.5,51.0,...,2.0,1.0,2.0,12.0,27.0,20.0,2.0,25.0,6.0,2.0
3,01005,Ambérieux-en-Dombes,1671.0,18.7,58.1,105.0,0.9,20.5,31.6,53.0,...,0.0,0.0,0.0,0.0,2.0,3.0,0.0,1.0,1.0,0.0
4,01006,Ambléon,110.0,28.6,173.3,18.7,-0.4,10.9,20.0,56.4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32724,85204,Saint-Christophe-du-Ligneron,2539.0,17.4,72.7,59.9,0.2,21.9,31.3,49.6,...,0.0,0.0,0.0,1.0,2.0,4.0,0.0,3.0,1.0,1.0
32725,85205,Saint-Cyr-des-Gâts,537.0,18.3,95.3,25.5,0.9,17.5,25.1,53.8,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32726,85206,Saint-Cyr-en-Talmondais,376.0,17.3,150.8,27.0,1.2,13.8,19.6,51.6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32727,85207,Saint-Denis-du-Payré,384.0,7.4,230.5,23.6,0.3,11.9,17.4,47.3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32728,85208,Saint-Denis-la-Chevasse,2299.0,18.5,57.3,58.2,1.0,22.1,32.7,51.3,...,0.0,0.0,0.0,0.0,2.0,3.0,0.0,0.0,1.0,1.0

In [9]:
for col in data.columns:
    print(col)

code
commune
pop
1_child-25
Indice_vieillissement
density_pop
evol_pop
pop-15y
pop-25y
pop-64y
pop+65y
fmly_no_child-25
fmly_2_child-25
fmly_3_child-25
mean_familiy_size
type_agglo
ratio_no_diploma
ratio_CAP_BEP
ratio_bac
ratio_etude_sup
res_princ_46
res_princ
res_second
log_vacants
appt
maison
propr
locataire
hlm
nb_crea_ent
nb_ent
part_0_sal
part-10sal
part+10sal
part_agri_x
part_indus
part_const
part_commerce
part_admin
part_salarié
part_non_salarié
part_agri_y
part_arti
part_cadre
part_employe
part_prof_inter
part_ouvrier
ta1
ta2
ta3
ta_femme
ta_homme
hypermarché
pôle emploi
banques
poste
epicerie
boulangerie
boucherie
maternelle
élémentaire
collège
urgences
lycee
dentiste
medecin
infirmier
creche
kine
pharmacie
epahd

In [10]:
data_num=data.iloc[:,2:]

In [11]:
print(data.shape)
print(data_num.shape)

(32729, 71)
(32729, 69)

In [12]:
def ratio_na(col):
    ratio = len(col[col.isna()])/len(col)
    return ratio
def nb_na(col):
    nb = len(col[col.isna()])
    return nb

In [13]:
for col in data_num:
    print('Column ', data_num[col].name, 'has ',nb_na(data_num[col]),' soit ',ratio_na(data_num[col]),'% of missing value')

Column  pop has  0  soit  0.0 % of missing value
Column  1_child-25 has  0  soit  0.0 % of missing value
Column  Indice_vieillissement has  0  soit  0.0 % of missing value
Column  density_pop has  0  soit  0.0 % of missing value
Column  evol_pop has  0  soit  0.0 % of missing value
Column  pop-15y has  0  soit  0.0 % of missing value
Column  pop-25y has  0  soit  0.0 % of missing value
Column  pop-64y has  0  soit  0.0 % of missing value
Column  pop+65y has  0  soit  0.0 % of missing value
Column  fmly_no_child-25 has  0  soit  0.0 % of missing value
Column  fmly_2_child-25 has  0  soit  0.0 % of missing value
Column  fmly_3_child-25 has  0  soit  0.0 % of missing value
Column  mean_familiy_size has  0  soit  0.0 % of missing value
Column  type_agglo has  0  soit  0.0 % of missing value
Column  ratio_no_diploma has  0  soit  0.0 % of missing value
Column  ratio_CAP_BEP has  0  soit  0.0 % of missing value
Column  ratio_bac has  0  soit  0.0 % of missing value
Column  ratio_etude_sup has  0  soit  0.0 % of missing value
Column  res_princ_46 has  0  soit  0.0 % of missing value
Column  res_princ has  0  soit  0.0 % of missing value
Column  res_second has  0  soit  0.0 % of missing value
Column  log_vacants has  0  soit  0.0 % of missing value
Column  appt has  0  soit  0.0 % of missing value
Column  maison has  0  soit  0.0 % of missing value
Column  propr has  0  soit  0.0 % of missing value
Column  locataire has  0  soit  0.0 % of missing value
Column  hlm has  0  soit  0.0 % of missing value
Column  nb_crea_ent has  0  soit  0.0 % of missing value
Column  nb_ent has  0  soit  0.0 % of missing value
Column  part_0_sal has  0  soit  0.0 % of missing value
Column  part-10sal has  0  soit  0.0 % of missing value
Column  part+10sal has  0  soit  0.0 % of missing value
Column  part_agri_x has  0  soit  0.0 % of missing value
Column  part_indus has  0  soit  0.0 % of missing value
Column  part_const has  0  soit  0.0 % of missing value
Column  part_commerce has  0  soit  0.0 % of missing value
Column  part_admin has  0  soit  0.0 % of missing value
Column  part_salarié has  0  soit  0.0 % of missing value
Column  part_non_salarié has  0  soit  0.0 % of missing value
Column  part_agri_y has  0  soit  0.0 % of missing value
Column  part_arti has  0  soit  0.0 % of missing value
Column  part_cadre has  0  soit  0.0 % of missing value
Column  part_employe has  0  soit  0.0 % of missing value
Column  part_prof_inter has  0  soit  0.0 % of missing value
Column  part_ouvrier has  0  soit  0.0 % of missing value
Column  ta1 has  0  soit  0.0 % of missing value
Column  ta2 has  0  soit  0.0 % of missing value
Column  ta3 has  0  soit  0.0 % of missing value
Column  ta_femme has  0  soit  0.0 % of missing value
Column  ta_homme has  0  soit  0.0 % of missing value
Column  hypermarché has  0  soit  0.0 % of missing value
Column  pôle emploi has  0  soit  0.0 % of missing value
Column  banques has  0  soit  0.0 % of missing value
Column  poste has  0  soit  0.0 % of missing value
Column  epicerie has  0  soit  0.0 % of missing value
Column  boulangerie has  0  soit  0.0 % of missing value
Column  boucherie has  0  soit  0.0 % of missing value
Column  maternelle has  0  soit  0.0 % of missing value
Column  élémentaire has  0  soit  0.0 % of missing value
Column  collège has  0  soit  0.0 % of missing value
Column  urgences has  0  soit  0.0 % of missing value
Column  lycee has  0  soit  0.0 % of missing value
Column  dentiste has  0  soit  0.0 % of missing value
Column  medecin has  0  soit  0.0 % of missing value
Column  infirmier has  0  soit  0.0 % of missing value
Column  creche has  0  soit  0.0 % of missing value
Column  kine has  0  soit  0.0 % of missing value
Column  pharmacie has  0  soit  0.0 % of missing value
Column  epahd has  0  soit  0.0 % of missing value

In [11]:
data_num.head()

,pop,1_child-25,Indice_vieillissement,density_pop,evol_pop,pop-15y,pop-25y,pop-64y,pop+65y,fmly_no_child-25,...,collège,urgences,lycee,dentiste,medecin,infirmier,creche,kine,pharmacie,epahd
0,767.0,19.1,67.5,48.1,-0.3,21.0,30.0,51.4,18.6,48.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,243.0,13.3,66.7,26.6,0.8,22.6,28.8,53.1,18.1,46.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,14081.0,24.8,62.1,572.4,0.3,19.8,32.5,51.0,16.5,44.9,...,2.0,1.0,2.0,12.0,27.0,20.0,2.0,25.0,6.0,2.0
3,1671.0,18.7,58.1,105.0,0.9,20.5,31.6,53.0,15.4,48.1,...,0.0,0.0,0.0,0.0,2.0,3.0,0.0,1.0,1.0,0.0
4,110.0,28.6,173.3,18.7,-0.4,10.9,20.0,56.4,23.6,57.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
data_num=np.array(data_num,dtype=float)

In [15]:
data_num

array([[7.6700e+02, 1.9100e+01, 6.7500e+01, ..., 1.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.4300e+02, 1.3300e+01, 6.6700e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.4081e+04, 2.4800e+01, 6.2100e+01, ..., 2.5000e+01, 6.0000e+00,
        2.0000e+00],
       ...,
       [3.7600e+02, 1.7300e+01, 1.5080e+02, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [3.8400e+02, 7.4000e+00, 2.3050e+02, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.2990e+03, 1.8500e+01, 5.7300e+01, ..., 0.0000e+00, 1.0000e+00,
        1.0000e+00]], shape=(32729, 69))

In [16]:
data_num.shape

(32729, 69)

In [17]:
error=0
column=None
for i in range(data_num.shape[1]):
    if type(data_num[0][i])!=np.float64:
        column=i
        error+=1
print(error)
print(column)

0
None

In [18]:
M=np.mean(data_num,0)

In [19]:
u=data_num-M
sigma=np.dot(u.T,u)
eigval,eigvec = np.linalg.eig(sigma)
print(eigval)

[7.74466339e+12 2.96345926e+10 2.95546172e+09 3.58693621e+08
 4.90353468e+07 2.92892068e+07 2.23899500e+07 2.07162761e+07
 1.49768583e+07 1.43972806e+07 1.22918164e+07 1.06226380e+07
 1.01562530e+07 9.51147191e+06 7.71226588e+06 7.13563886e+06
 6.32313871e+06 5.36369784e+06 5.27834442e+06 4.36355500e+06
 4.25376026e+06 3.20216846e+06 3.12224079e+06 2.96240722e+06
 2.50144249e+06 2.05773354e+06 1.55942811e+06 1.37665890e+06
 1.30258475e+06 1.07194396e+06 9.03562919e+05 8.72277451e+05
 7.94380054e+05 7.10914423e+05 5.15594892e+05 4.57991287e+05
 4.24548036e+05 3.62046164e+05 3.05168486e+05 2.13893080e+05
 1.25047149e+05 1.33862772e+05 8.08739554e+04 7.86706025e+04
 7.36331707e+04 6.84021622e+04 6.30006435e+04 4.95212968e+04
 5.83621477e+04 3.26984382e+04 2.36099901e+04 1.51685587e+04
 1.00225203e+04 9.53372065e+03 8.51336112e+03 7.95867888e+03
 6.96539526e+03 5.29254741e+03 5.60945044e+03 3.56240610e+03
 2.24290273e+03 1.21661268e+03 3.90127680e+02 3.48550434e+02
 1.44749098e+01 2.48670654e+01 2.71000789e+01 2.75730988e+01
 2.65801380e+01]

In [20]:
idx = eigval.argsort()[::-1]
print(idx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 41 40 42 43 44 45 46 48
 47 49 50 51 52 53 54 55 56 58 57 59 60 61 62 63 67 66 68 65 64]

In [21]:
print(eigvec[0][:])

[ 9.86095669e-01  1.62522245e-01 -3.42564050e-02 -4.50089533e-05
 -3.77361097e-04  3.64987991e-04  2.08521568e-03 -2.38680357e-03
 -7.70395401e-04 -7.83188291e-04  3.23404483e-04  8.19149471e-05
 -7.83867454e-04 -7.10297389e-04 -3.45962579e-04 -5.41827284e-05
 -3.05506191e-04 -6.21146468e-04  1.12463821e-04  7.20107784e-06
  7.53519766e-05  1.29931643e-03 -3.10784035e-03  7.78849830e-04
  2.34549478e-04 -1.21072923e-04  1.19956672e-04 -2.77381941e-05
  7.96686397e-06  2.18285519e-05 -6.98321320e-05 -5.04095126e-05
  1.98079657e-05  2.82142705e-05 -9.20239962e-07  3.90209366e-04
  7.40771047e-05  1.10767914e-03 -2.61832154e-04  7.69347302e-06
  1.03054164e-03 -2.10983157e-05  6.59719416e-05  7.17308501e-05
 -6.00280225e-05 -2.23239557e-04  2.77623685e-05  1.90878126e-04
 -2.99421745e-07 -1.80999645e-04  1.73519293e-04  2.17428793e-04
 -8.75910733e-05 -3.95085383e-04  6.51511797e-05 -9.44222050e-05
  1.01585444e-04 -2.50527200e-05 -1.47972633e-06 -8.89852907e-05
  6.61946773e-06  2.73312595e-05 -3.02447191e-06  2.73011872e-06
 -1.58808915e-08 -5.35679091e-08  2.51275813e-07 -1.65624215e-08
  4.55678930e-09]

In [22]:
eigvec=eigvec[:,idx]

In [25]:
newData=np.dot(u,np.real(eigvec[:,:50]))

In [24]:
np.save('../data/data_from_pca/newData40',newData)
np.save('../data/data_from_pca/eigval',eigval)
np.save('../data/data_from_pca/eigvec',eigvec)